<!DOCTYPE html>
<html lang=en>
           <head>
            <meta charset=UTF-8>
            <title>Trapping foreign calls to exit()</title>
            <meta name=viewport
                  content="width=device-width, initial-scale=1.0">
            <link rel=stylesheet
                  href=https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css
                  integrity=sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2
                  crossorigin=anonymous>
            <style>
section.tree {
    padding-left: 2em;
}
section.tree:first-child {
    padding-left: 0;
}
.article-link {
  margin-bottom: 1em;
}
</style>
<!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9X3G9MMWZP"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9X3G9MMWZP');
</script>

           </head>
           <body>
            <header class="d-flex justify-content-center">
             <nav
                  class="navbar navbar-light bg-light w-100 mx-5 mb-3">
              <a class=navbar-brand href="/">Lisp HUG Maillist Archive</a>
             </nav>
            </header>
            <div class="d-flex justify-content-center">
             <div class="w-100 mx-5 px-3">
              <section class=tree>
               <article class=email>
                <h1>Trapping foreign calls to exit()</h1>
                <pre>
Is it possible to trap these so LispWorks doesn't just quit? I found a ..ps file talking about doing this, but it was from 2004 using a very old LW FFI and a foreign-callable that doesn't even match the current define-foreign-callable.

Thanks for any thoughts.

Jeff M.

</pre>
               </article>
               <section class=tree>
                <article class=email>
                 <h1>Re: Trapping foreign calls to exit()</h1>
                 <pre>
Note:

If I define a foreign callable which throws an error and passed it to atexit(). Calling exit on my own seems to trap it, throw the error and not exit LispWorks. Yet, when exit() is called from the foreign library, it still quitsâ€¦

Jeff M.

On Oct 9, 2011, at 10:23 AM, Jeffrey Massung wrote:

&gt Is it possible to trap these so LispWorks doesn't just quit? I found a ..ps file talking about doing this, but it was from 2004 using a very old LW FFI and a foreign-callable that doesn't even match the current define-foreign-callable.
&gt 
&gt Thanks for any thoughts.
&gt 
&gt Jeff M.


</pre>
                </article>
               </section>
              </section>
             </div>
            </div>
            <footer class="d-flex justify-content-center">
             <div>
              Updated at: 2020-12-10 08:37 UTC
             </div>
            </footer>
           </body>
          </html>